### ISSUE TITLE
Ken Griffey Jr. Presents Major League Baseball

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/SNES_MiSTer#20]
When selecting the option "Season" for the game mode it doesn't work. You will see a weird graphical glitch and the game either freezes up or resets.

**Comment by James-F2** [comment]
Confirmed.

**Comment by James-F2** [comment]
Fixed

**Comment by James-F2** [comment]
Looks like it was fixed.
Some commit from March 3rd or 4th fixed this bug.
Needs confirmation by another person and close.

**Comment by James-F2** [comment]
Confirmed to be fixed by others.

Main MiSTer had too be updated too, probably because of this:
> Report image size 0 if no save available

**Comment by RetroDriven** [comment]
I'm running the latest Mister main and SNES Core but I'm still having the same issue. Maybe it's my Rom?

**Comment by James-F2** [comment]
Sorry forgot to mention that it is with March 4th commits that I compiled, they will be included with the next release.

**Comment by James-F2** [comment]
Works perfectly with latest release.
